### ISSUE TITLE
mango分库时，将配置信息迁移到apollo的时候，一直无法读取mango配置信息mango.scan-package

### ISSUE THREAD

**Issue by TreeZhiyuan** [jfaster/mango-spring-boot-starter#5]
可以肯定的是apollo的配置是没问题的，只是Mango在从Apollo读取配置信息的时候无法读取到，导致报如下错误：
org.jfaster.mango.plugin.spring.exception.MangoAutoConfigException: mango.scan-package is not configured
	at org.jfaster.mango.plugin.spring.starter.MangoDaoAutoCreator.postProcessBeanFactory(MangoDaoAutoCreator.java:88) ~[mango-spring-boot-starter-0.3.jar!/:0.3]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:283) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:178) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
	at cn.cloudbae.mechant.MechantApplication.main(MechantApplication.java:42) [classes!/:2.6.1.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [cloudbae-merchant-2.6.1.RELEASE.jar:2.6.1.RELEASE]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [cloudbae-merchant-2.6.1.RELEASE.jar:2.6.1.RELEASE]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [cloudbae-merchant-2.6.1.RELEASE.jar:2.6.1.RELEASE]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [cloudbae-merchant-2.6.1.RELEASE.jar:2.6.1.RELEASE]

**Comment by TreeZhiyuan** [comment]
fixed this issue long long age, close it
